'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

type Mood = 'chaos' | 'calm' | 'contrast';
type Motion = 'push' | 'pull' | 'drift';
type Scene = { headline: string; body: string; accent: string; marks: string[]; mood: Mood; motion: Motion };
type Project = { presetId: string; hook: string; sceneA: Scene; sceneB: Scene; durationA: number; durationB: number; audio: 'none' | 'ig_safe' | 'original'; abTest: boolean; originalReupload: boolean };
type Packet = { hook: string; body: string; tags: string[]; commentPrompt: string };
type Preset = { id: string; title: string; sceneA: Scene; sceneB: Scene; motionHint: string; durationDefault: number; forbiddenTemplates: string[]; format: 'reel' };
type View = 'studio' | 'edit' | 'cut' | 'production' | 'bots' | 'library' | 'agent' | 'connect' | 'packet' | 'gates' | 'export';

const initialPacket: Packet = {
  hook: 'ChatGPT when you say make it professional',
  body: 'The email was never the work.\nThe twelve-line greeting was.\nMake the ask clear and send it.',
  tags: ['#aiatwork', '#email', '#prompts'],
  commentPrompt: 'You edit work emails.\nMax 6 lines. One ask.\nNo greeting essay. No recap. No "happy to help".\nOutput: subject + body.',
};

const makeScene = (headline: string, body: string, mood: Mood, accent: string, marks: string[], motion: Motion): Scene => ({ headline, body, mood, accent, marks, motion });

const presets: Preset[] = [
  { id: 'unpaid-intern-email', title: 'Unpaid intern email', sceneA: makeScene('boss: make it professional with AI', 'Hope this finds you well...\nHappy to jump on a call...\nPlease don’t hesitate...', 'chaos', 'A 47-word greeting for a six-line email.', ['Three greetings', 'No actual ask', 'Calendar bait'], 'push'), sceneB: makeScene('You needed 6 lines.', 'You edit work emails.\nMax 6 lines. One ask.\nNo greeting essay.\nOutput: subject + body.', 'calm', 'The prompt that ships.', ['One ask', 'Clear subject', 'Ready to send'], 'pull'), motionHint: 'Fast push into the greeting pile, then pull out on the useful prompt.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
  { id: 'meeting-recap', title: 'Meeting recap nobody asked for', sceneA: makeScene('AI: here is your 47-line recap', 'Context. Context. Context.\nA summary of the summary.\nNo decision in sight.', 'chaos', 'The meeting ended. The novel began.', ['47 lines', 'No owner', 'No decision'], 'push'), sceneB: makeScene('4 bullets + one ask', 'Decision: approve the brief.\nOwner: Maya.\nDeadline: Thursday.\nAsk: reply with blockers.', 'calm', 'The recap people can use.', ['Decision', 'Owner', 'Deadline'], 'pull'), motionHint: 'Zoom into the wall of text. Cut to the four bullets.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
  { id: 'calendar-spam', title: 'Calendar spam', sceneA: makeScene('Happy to jump on a call anytime', 'Monday? Tuesday?\nThursday works too.\nLet’s find time to find time.', 'chaos', 'Calendar Tetris, unpaid.', ['No options', 'No timezone', 'No question'], 'push'), sceneB: makeScene('Two times. One timezone. One question.', 'Tue 14:00 ET or Wed 10:30 ET?\nWhich works for the approval?', 'contrast', 'A calendar invite is not a quest.', ['Two options', 'Timezone', 'One decision'], 'drift'), motionHint: 'Push through the calendar noise, soft drift on the answer.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
  { id: 'attachment-theatre', title: 'Attachment theatre', sceneA: makeScene('Kindly find attached hereof', 'Please see the attached attachment\nfor your kind perusal\nand favourable consideration.', 'chaos', 'The file is doing theatre.', ['No file name', 'No action', 'Three formalities'], 'push'), sceneB: makeScene('The file + what to do with it.', 'Attached: Q3 budget.xlsx\nPlease approve rows 18–24 by Friday.', 'calm', 'Name it. Ask for something.', ['File named', 'One action', 'Deadline'], 'pull'), motionHint: 'Fast push, then an intentional pull-out.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
  { id: 'slack-to-email', title: 'Slack-to-email', sceneA: makeScene('A Slack ping becomes a novel', 'Hey! Just circling back 😊\nI wanted to gently flag\na tiny little thing...', 'chaos', 'AI found every filler word.', ['Novel energy', 'Emoji spill', 'No subject'], 'push'), sceneB: makeScene('Subject + five lines. Done.', 'Subject: Review needed by 3pm\nCan you approve the brief?\nTwo edits are highlighted.\nReply yes or send blockers.', 'calm', 'No “just circling back.”', ['Subject', 'Five lines', 'Clear ask'], 'pull'), motionHint: 'Crash zoom into the filler, hard cut to the useful version.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
  { id: 'macbook-laptop', title: 'MacBook vs gaming laptop', sceneA: makeScene('Overkill setup. Overkill prompt.', 'Act as a genius boardroom\nwith 14 expert personas\nwho also know my soul.', 'chaos', 'RGB prompt engineering.', ['14 personas', 'No task', 'Maximum theatre'], 'push'), sceneB: makeScene('Boring machine. Boring prompt. Ships.', 'Write a launch email.\nAudience: existing users.\nOne benefit. One CTA.\nMax 120 words.', 'contrast', 'Boring prompt. Useful output.', ['Audience', 'Constraint', 'CTA'], 'drift'), motionHint: 'Aggressive push on the overkill, quiet drift on the prompt.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
  { id: 'docs-nobody-reads', title: 'Docs nobody reads', sceneA: makeScene('A 12-page “strategy”', 'Vision. Mission. Synergy.\nPage 8 has a chart.\nNo one knows who decides.', 'chaos', 'Slides dressed up as a decision.', ['12 pages', 'No owner', 'No decision'], 'push'), sceneB: makeScene('One page. One decision. One owner.', 'Decision: run the pilot.\nOwner: Jordan.\nSuccess: 25 qualified demos.\nNext: approve budget.', 'calm', 'If it cannot decide, it cannot ship.', ['One page', 'Owner', 'Next step'], 'pull'), motionHint: 'Dive into the deck, cut cleanly to the decision.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
  { id: 'per-my-last-email', title: 'Per my last email', sceneA: makeScene('AI wrote “per my last email”', 'As previously communicated,\nI would appreciate it if you\nwould kindly revisit my note.', 'chaos', 'Passive aggression, now automated.', ['Temperature 100', 'No fact', 'No ask'], 'push'), sceneB: makeScene('Fact + ask. No temperature.', 'The invoice is still open.\nCan you confirm payment by Thursday?', 'contrast', 'Cold facts. Warm blood pressure.', ['Fact', 'One ask', 'No smoke'], 'drift'), motionHint: 'Push into the passive-aggressive cloud. Cut to the fact.', durationDefault: 10, forbiddenTemplates: ['drake', 'ivory_textbook', 'hangul_quote'], format: 'reel' },
];

const blankProject: Project = { presetId: presets[0].id, hook: presets[0].sceneA.headline, sceneA: presets[0].sceneA, sceneB: presets[0].sceneB, durationA: 5, durationB: 5, audio: 'none', abTest: false, originalReupload: false };
const nav: { href: string; label: string; view: View }[] = [{ href: '/', label: 'Studio', view: 'studio' }, { href: '/edit', label: 'Edit lab', view: 'edit' }, { href: '/cut', label: 'Cut log', view: 'cut' }, { href: '/production', label: 'Production', view: 'production' }, { href: '/bots', label: 'Bot check', view: 'bots' }, { href: '/library', label: 'Library', view: 'library' }, { href: '/agent', label: 'Agent desk', view: 'agent' }, { href: '/connect', label: 'Local desk', view: 'connect' }, { href: '/packet', label: 'Packet', view: 'packet' }, { href: '/gates', label: 'Gate board', view: 'gates' }, { href: '/export', label: 'Export', view: 'export' }];

function safeRead<T>(key: string, fallback: T): T { try { const value = window.localStorage.getItem(key); return value ? (JSON.parse(value) as T) : fallback; } catch { return fallback; } }
function hasHangul(value: string) { return /[\uAC00-\uD7A3]/.test(value); }
function wordSimilarity(a: string, b: string) { const one = new Set(a.toLowerCase().match(/[a-z0-9]+/g) ?? []); const two = new Set(b.toLowerCase().match(/[a-z0-9]+/g) ?? []); const common = [...one].filter((word) => two.has(word)).length; return common / Math.max(1, new Set([...one, ...two]).size); }
function todaySeoul() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); }
function isEnglish(value: string) { return !hasHangul(value) && /[a-zA-Z]/.test(value); }

function sceneScale(scene: Scene, progress: number) { if (scene.motion === 'pull') return 1.22 - progress * .16; if (scene.motion === 'drift') return 1.05 + Math.sin(progress * Math.PI) * .08; return 1 + progress * .22; }

function SceneCanvas({ scene, label, active, progress, onChange }: { scene: Scene; label: 'A' | 'B'; active: boolean; progress: number; onChange?: (scene: Scene) => void }) {
  const update = (field: keyof Scene, value: string) => onChange?.({ ...scene, [field]: value });
  return <section className={`scene-panel mood-${scene.mood} ${active ? 'live-scene' : ''}`}>
    <div className="scene-panel-top"><span>SCENE {label}</span><span className="scene-format">1080 × 1920</span></div>
    <div className="scene-canvas-wrap">
      <div className="scene-canvas" style={{ transform: `scale(${sceneScale(scene, progress)})` }}>
        <span className="canvas-noh">NOH</span>
        <span className="canvas-index">0{label}</span>
        <h2>{scene.headline}</h2>
        <p>{scene.body}</p>
        <strong>{scene.accent}</strong>
        <ul>{scene.marks.map((mark, index) => <li key={`${mark}-${index}`} className={label === 'A' ? 'bad' : 'good'}><i>{label === 'A' ? '×' : '✓'}</i>{mark}</li>)}</ul>
      </div>
    </div>
    {onChange && <div className="scene-editor">
      <label>Headline<input value={scene.headline} onChange={(event) => update('headline', event.target.value)} /></label>
      <label>Body<textarea rows={3} value={scene.body} onChange={(event) => update('body', event.target.value)} /></label>
      <label>Accent<input value={scene.accent} onChange={(event) => update('accent', event.target.value)} /></label>
      <div className="scene-options"><label>Mood<select value={scene.mood} onChange={(event) => onChange({ ...scene, mood: event.target.value as Mood })}><option value="chaos">chaos</option><option value="calm">calm</option><option value="contrast">contrast</option></select></label><label>Camera<select value={scene.motion} onChange={(event) => onChange({ ...scene, motion: event.target.value as Motion })}><option value="push">push in</option><option value="pull">pull out</option><option value="drift">soft drift</option></select></label></div>
    </div>}
  </section>;
}

function GateStrip({ gates, compact = false }: { gates: GateResult[]; compact?: boolean }) {
  return <div className={`gate-strip ${compact ? 'compact' : ''}`}>{gates.map((gate) => <div className={`gate-chip ${gate.pass ? 'pass' : 'fail'}`} key={gate.id}><span>{gate.pass ? '✓' : '×'}</span><div><b>GATE {gate.id}</b><small>{gate.pass ? gate.passText : gate.failText}</small></div></div>)}</div>;
}

type GateResult = { id: 'A' | 'B' | 'C'; pass: boolean; passText: string; failText: string; points: string[] };

function useForge() {
  const [project, setProject] = useState<Project>(blankProject);
  const [packet, setPacket] = useState<Packet>(initialPacket);
  const [lastTemplates, setLastTemplates] = useState<string[]>([]);
  const [lastHooks, setLastHooks] = useState<{ hook: string; at: number }[]>([]);
  const [slots, setSlots] = useState<Record<string, number>>({});
  const [ready, setReady] = useState(false);
  useEffect(() => { const saved = safeRead<Project>('currentProject', blankProject); setProject(saved?.sceneA && saved?.sceneB ? saved : blankProject); setPacket(safeRead<Packet>('packet', initialPacket)); setLastTemplates(safeRead<string[]>('last7Templates', [])); setLastHooks(safeRead<{ hook: string; at: number }[]>('last7Hooks', [])); setSlots(safeRead<Record<string, number>>('slotCountByDate', {})); setReady(true); }, []);
  useEffect(() => { if (ready) { window.localStorage.setItem('currentProject', JSON.stringify(project)); window.localStorage.setItem('packet', JSON.stringify(packet)); window.localStorage.setItem('last7Templates', JSON.stringify(lastTemplates.slice(0, 7))); window.localStorage.setItem('last7Hooks', JSON.stringify(lastHooks.slice(0, 7))); window.localStorage.setItem('slotCountByDate', JSON.stringify(slots)); } }, [project, packet, lastTemplates, lastHooks, slots, ready]);
  const templateBlocked = lastTemplates.includes(project.presetId);
  const hookBlocked = lastHooks.some((entry) => entry.hook.trim().toLowerCase() === project.hook.trim().toLowerCase() && Date.now() - entry.at < 8 * 60 * 60 * 1000);
  const gates = useMemo<GateResult[]>(() => {
    const allCopy = [project.sceneA.headline, project.sceneA.body, project.sceneA.accent, project.sceneB.headline, project.sceneB.body, project.sceneB.accent];
    const longDeck = project.sceneA.body.split('\n').length > 7 || project.sceneB.body.split('\n').length > 7;
    const copyPass = allCopy.every(isEnglish) && !longDeck;
    const similar = wordSimilarity(`${project.sceneA.headline} ${project.sceneA.body}`, `${project.sceneB.headline} ${project.sceneB.body}`) >= .8;
    const scenePass = !similar && project.sceneA.motion !== project.sceneB.motion && !project.originalReupload && !templateBlocked && !hookBlocked && project.durationA + project.durationB >= 8 && project.durationA + project.durationB <= 12 && !project.abTest && (slots[todaySeoul()] ?? 0) < 2;
    const packetPass = Boolean(packet.hook.trim() && packet.body.trim() && packet.tags.filter(Boolean).length && packet.commentPrompt.trim());
    return [
      { id: 'A', pass: copyPass, passText: 'English copy, one hook', failText: 'English only on the reel', points: ['English only', 'One-hook dialogue structure', 'Not a 7-page deck', 'No ivory textbook treatment'] },
      { id: 'B', pass: scenePass, passText: 'Two worlds. One hard cut.', failText: similar ? 'A and B must be different scenes' : project.sceneA.motion === project.sceneB.motion ? 'Same camera, not a recreate' : templateBlocked ? 'Template used in last 7' : hookBlocked ? 'Hook used in last 8 hours' : project.abTest ? 'A/B test. Do not Share.' : (slots[todaySeoul()] ?? 0) >= 2 ? 'Daily Reel slots are full' : 'This would die on the real account.', points: ['Two distinct 9:16 scenes', 'Different copy and motion', 'Hard cut only', 'No stretched square image'] },
      { id: 'C', pass: packetPass, passText: 'Caption packet ready', failText: 'Chat-only caption = Gate C fail', points: ['Hook, body, tags, Comment PROMPT', 'Up to five tags', 'Useful and funny'] },
    ];
  }, [project, packet, templateBlocked, hookBlocked, slots]);
  const allGreen = gates.every((gate) => gate.pass);
  const recordExport = () => { const date = todaySeoul(); setSlots((value) => ({ ...value, [date]: (value[date] ?? 0) + 1 })); setLastTemplates((value) => [project.presetId, ...value.filter((id) => id !== project.presetId)].slice(0, 7)); setLastHooks((value) => [{ hook: project.hook, at: Date.now() }, ...value.filter((entry) => entry.hook.toLowerCase() !== project.hook.toLowerCase())].slice(0, 7)); };
  return { project, setProject, packet, setPacket, lastTemplates, lastHooks, slots, gates, allGreen, recordExport };
}

function Topbar({ view, slots }: { view: View; slots: Record<string, number> }) {
  return <header className="forge-header"><a href="/" className="wordmark"><span>NOH</span><i>Reel Forge</i></a><nav aria-label="Primary navigation">{nav.map((item) => <a className={item.view === view ? 'current' : ''} href={item.href} key={item.href}>{item.label}</a>)}</nav><div className="header-meta"><span>Reel slots today: {slots[todaySeoul()] ?? 0} / 2</span><b>Created with Grok</b></div></header>;
}

function Timeline({ project, setProject, playing, playhead, onPlay, onScrub }: { project: Project; setProject: (project: Project) => void; playing: boolean; playhead: number; onPlay: () => void; onScrub: (time: number) => void }) {
  const total = project.durationA + project.durationB;
  return <section className="timeline-card"><div className="timeline-head"><div><span>SEQUENCE</span><b>A block <i>| CUT |</i> B block</b></div><button className="play-button" onClick={onPlay}>{playing ? 'Playing' : `Play ${total}s`} <span>{playing ? '■' : '▶'}</span></button></div><div className="timeline-track"><div className="clip clip-a" style={{ width: `${project.durationA / total * 100}%` }}><span>SCENE A</span><small>zoom {project.sceneA.motion}</small></div><div className="cut"><i />CUT</div><div className="clip clip-b" style={{ width: `${project.durationB / total * 100}%` }}><span>SCENE B</span><small>{project.sceneB.motion} move</small></div><div className="playhead" style={{ left: `${playhead / total * 100}%` }} /></div><input aria-label="Scrub reel preview" className="scrubber" type="range" min="0" max={total} step="0.05" value={playhead} onChange={(event) => onScrub(Number(event.target.value))} /><div className="timing-controls"><label>A duration <input type="number" min="4" max="8" step=".5" value={project.durationA} onChange={(event) => setProject({ ...project, durationA: Number(event.target.value) })} /> sec</label><label>B duration <input type="number" min="4" max="8" step=".5" value={project.durationB} onChange={(event) => setProject({ ...project, durationB: Number(event.target.value) })} /> sec</label><span>30 fps · hard cut only</span></div></section>;
}

function Studio({ forge }: { forge: ReturnType<typeof useForge> }) {
  const { project, setProject, gates, allGreen, slots } = forge;
  const [playing, setPlaying] = useState(false);
  const [playhead, setPlayhead] = useState(0);
  const raf = useRef<number | null>(null);
  useEffect(() => { if (!playing) return; const start = performance.now() - playhead * 1000; const total = (project.durationA + project.durationB) * 1000; const tick = (now: number) => { setPlayhead(((now - start) % total) / 1000); raf.current = requestAnimationFrame(tick); }; raf.current = requestAnimationFrame(tick); return () => { if (raf.current) cancelAnimationFrame(raf.current); }; }, [playing, project.durationA, project.durationB]);
  const progressA = Math.min(1, playhead / project.durationA); const progressB = Math.min(1, Math.max(0, playhead - project.durationA) / project.durationB); const showingA = playhead < project.durationA;
  return <main className="forge-main studio-main"><section className="studio-title"><div><p className="kicker">NOH · REEL FORGE</p><h1>Emotional recreate.<br /><span>Not two PNGs taped together.</span></h1></div><div className="studio-actions"><label className="audio-select">Audio<select value={project.audio} onChange={(event) => setProject({ ...project, audio: event.target.value as Project['audio'] })}><option value="none">none</option><option value="ig_safe">ig_safe</option><option value="original">original</option></select></label><button className={`test-switch ${project.abTest ? 'on' : ''}`} onClick={() => setProject({ ...project, abTest: !project.abTest })}><i /> {project.abTest ? 'A/B TEST — DO NOT SHARE' : 'REAL MEME'}</button></div></section><GateStrip gates={gates} /><p className="empty-copy">Pick a situation. Two different worlds. One cut.</p><section className="scene-grid"><SceneCanvas label="A" scene={project.sceneA} active={showingA} progress={progressA} onChange={(sceneA) => setProject({ ...project, sceneA, hook: sceneA.headline })} /><SceneCanvas label="B" scene={project.sceneB} active={!showingA} progress={progressB} onChange={(sceneB) => setProject({ ...project, sceneB })} /></section><div className="live-preview"><span>LIVE PREVIEW · {showingA ? 'SCENE A' : 'SCENE B'}</span><div className={`preview-stage mood-${showingA ? project.sceneA.mood : project.sceneB.mood}`}><div style={{ transform: `scale(${sceneScale(showingA ? project.sceneA : project.sceneB, showingA ? progressA : progressB)})` }}><small>NOH</small><b>{showingA ? project.sceneA.headline : project.sceneB.headline}</b><p>{showingA ? project.sceneA.accent : project.sceneB.accent}</p></div></div></div><Timeline project={project} setProject={setProject} playing={playing} playhead={playhead} onPlay={() => setPlaying((value) => !value)} onScrub={(time) => { setPlaying(false); setPlayhead(time); }} /><section className="studio-bottom"><label className="toggle-row"><input type="checkbox" checked={project.originalReupload} onChange={(event) => setProject({ ...project, originalReupload: event.target.checked })} /> Original post re-upload</label><a className={`export-link ${allGreen ? '' : 'locked'}`} href="/export">{allGreen ? 'Export (gates green only) ↗' : 'Export locked — fix gates first'}</a><span>Today: {slots[todaySeoul()] ?? 0} / 2 Reel slots</span></section></main>;
}

function Library({ forge }: { forge: ReturnType<typeof useForge> }) { const { project, setProject, lastTemplates } = forge; const select = (preset: Preset) => setProject({ ...project, presetId: preset.id, hook: preset.sceneA.headline, sceneA: preset.sceneA, sceneB: preset.sceneB, durationA: 5, durationB: 5 }); return <main className="forge-main subpage"><section className="page-intro"><p className="kicker">SITUATION MEMES</p><h1>Library</h1><p>Choose a workplace feeling. Then make the second world genuinely different.</p></section><section className="preset-grid">{presets.map((preset, index) => { const used = lastTemplates.includes(preset.id); return <article className={`preset-card ${project.presetId === preset.id ? 'selected' : ''}`} key={preset.id}><span>0{index + 1}</span><h2>{preset.title}</h2><p>A: {preset.sceneA.headline}</p><p>B: {preset.sceneB.headline}</p><small>{preset.motionHint}</small><button onClick={() => select(preset)}>{used ? 'Use again — Gate B will block' : project.presetId === preset.id ? 'Loaded' : 'Load preset'} <i>↗</i></button></article>; })}</section><section className="recent-panel"><div><p className="kicker">RECENT 7</p><h2>Template guard</h2></div><p>{lastTemplates.length ? lastTemplates.map((id) => presets.find((preset) => preset.id === id)?.title ?? id).join(' · ') : 'No template has been exported yet. Your first reel is clear.'}</p></section></main>; }

function PacketEditor({ forge }: { forge: ReturnType<typeof useForge> }) { const { packet, setPacket, gates } = forge; const [tagInput, setTagInput] = useState(packet.tags.join(' ')); const updateTags = (value: string) => { setTagInput(value); setPacket({ ...packet, tags: value.split(/[\s,]+/).filter(Boolean).slice(0, 5) }); }; return <main className="forge-main subpage"><section className="page-intro"><p className="kicker">CAPTION PACKET</p><h1>Make the post useful after the laugh.</h1><p>Chat-only caption = Gate C fail. Save the real packet below.</p></section><div className="packet-layout"><form className="packet-form" onSubmit={(event) => event.preventDefault()}><label>Hook<input value={packet.hook} onChange={(event) => setPacket({ ...packet, hook: event.target.value })} /></label><label>Body <small>3–5 useful lines</small><textarea rows={5} value={packet.body} onChange={(event) => setPacket({ ...packet, body: event.target.value })} /></label><label>Tags <small>up to 5</small><input value={tagInput} onChange={(event) => updateTags(event.target.value)} placeholder="#aiatwork #email #prompts" /></label><label>Comment PROMPT<textarea rows={6} value={packet.commentPrompt} onChange={(event) => setPacket({ ...packet, commentPrompt: event.target.value })} /></label></form><aside className="packet-preview"><span>POST PREVIEW</span><h2>{packet.hook || 'A sharp hook goes here.'}</h2><p>{packet.body || 'The useful caption lives here.'}</p><b>{packet.tags.join(' ')}</b><hr /><small>COMMENT PROMPT</small><pre>{packet.commentPrompt || 'A copyable prompt belongs here.'}</pre></aside></div><GateStrip gates={gates} /></main>; }

function GateBoard({ forge }: { forge: ReturnType<typeof useForge> }) { const { gates, project } = forge; return <main className="forge-main subpage"><section className="page-intro gate-intro"><p className="kicker">QUALITY CONTROL</p><h1>Gate board</h1><p>This would die on the real account.</p></section><GateStrip gates={gates} /><section className="gate-board">{gates.map((gate) => <article key={gate.id} className={`gate-board-card ${gate.pass ? 'pass' : 'fail'}`}><div><span>GATE {gate.id}</span><b>{gate.pass ? 'PASS' : 'FAIL'}</b></div><h2>{gate.id === 'A' ? 'Copy' : gate.id === 'B' ? 'Scene and format' : 'Caption packet'}</h2><p>{gate.pass ? gate.passText : gate.failText}</p><ul>{gate.points.map((point) => <li key={point}>{point}</li>)}</ul></article>)}</section><section className="rule-panel"><div><span>NON-NEGOTIABLE</span><h2>Hard cut, not a crossfade.</h2></div><div><p>Total duration</p><b>{project.durationA + project.durationB}s / 8–12s</b></div><div><p>Audio</p><b>{project.audio}</b></div><div><p>Template</p><b>{project.presetId}</b></div></section></main>; }

function drawWrapped(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, width: number, line: number) { let current = ''; let row = 0; text.split(/\s+/).forEach((word) => { const test = `${current}${word} `; if (ctx.measureText(test).width > width) { ctx.fillText(current, x, y + row * line); current = `${word} `; row += 1; } else current = test; }); if (current) ctx.fillText(current, x, y + row * line); return y + (row + 1) * line; }

function ExportRoom({ forge }: { forge: ReturnType<typeof useForge> }) {
  const { project, allGreen, gates, recordExport } = forge; const [url, setUrl] = useState(''); const [status, setStatus] = useState(''); const [exporting, setExporting] = useState(false); const [copied, setCopied] = useState(false); const validReel = url.includes('/reel/'); const postUrl = url.includes('/p/'); const permalinkText = validReel ? 'Reels menu. Good.' : postUrl ? 'You opened the post menu. This is not a reel.' : url ? 'Paste an Instagram /reel/ permalink.' : 'Check the reel after publishing.';
  const recipe = `ffmpeg -loop 1 -i scene-a.png -loop 1 -i scene-b.png -filter_complex "[0:v]scale=1080:1920,zoompan=z='min(zoom+0.0015,1.22)':d=150[a];[1:v]scale=1080:1920,zoompan=z='if(lte(on,0),1.22,max(1.06,zoom-0.001))':d=150[b];[a][b]concat=n=2:v=1:a=0" -r 30 noh-reel.mp4`;
  const startExport = () => { if (!allGreen || exporting) return; if (!('MediaRecorder' in window)) { setStatus('WebM is not available in this browser. Copy the ffmpeg zoom + cut recipe instead.'); return; } try { setExporting(true); setStatus('Rendering a WebM in this browser. Keep this tab open for 10 seconds.'); const canvas = document.createElement('canvas'); canvas.width = 1080; canvas.height = 1920; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Canvas is unavailable'); const stream = canvas.captureStream(30); const mime = MediaRecorder.isTypeSupported('video/webm;codecs=vp9') ? 'video/webm;codecs=vp9' : 'video/webm'; const recorder = new MediaRecorder(stream, { mimeType: mime }); const chunks: BlobPart[] = []; recorder.ondataavailable = (event) => { if (event.data.size) chunks.push(event.data); }; recorder.onstop = () => { const blob = new Blob(chunks, { type: mime }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'noh-reel-forge.webm'; link.click(); window.setTimeout(() => URL.revokeObjectURL(link.href), 1000); recordExport(); setExporting(false); setStatus('WebM exported. This app did not create an MP4.'); }; const total = (project.durationA + project.durationB) * 1000; const start = performance.now(); const draw = (now: number) => { const elapsed = Math.min(now - start, total); const isA = elapsed < project.durationA * 1000; const scene = isA ? project.sceneA : project.sceneB; const segment = isA ? elapsed / (project.durationA * 1000) : (elapsed - project.durationA * 1000) / (project.durationB * 1000); const scale = sceneScale(scene, segment); ctx.fillStyle = scene.mood === 'chaos' ? '#17110c' : scene.mood === 'calm' ? '#0d1712' : '#101018'; ctx.fillRect(0, 0, 1080, 1920); ctx.save(); ctx.translate(540, 960); ctx.scale(scale, scale); ctx.translate(-540, -960); ctx.fillStyle = '#f5c400'; ctx.font = '700 42px Arial'; ctx.fillText('NOH', 80, 115); ctx.fillStyle = '#ffffff'; ctx.font = '800 96px Arial'; let next = drawWrapped(ctx, scene.headline, 80, 610, 880, 114); ctx.fillStyle = '#b8b8b8'; ctx.font = '500 42px Arial'; next = drawWrapped(ctx, scene.body.replace(/\n/g, ' '), 80, next + 70, 870, 60); ctx.fillStyle = '#f5c400'; ctx.font = '700 46px Arial'; drawWrapped(ctx, scene.accent, 80, Math.max(next + 100, 1450), 870, 58); ctx.restore(); if (elapsed < total) requestAnimationFrame(draw); else recorder.stop(); }; recorder.start(); requestAnimationFrame(draw); } catch { setExporting(false); setStatus('WebM export could not start. Copy the ffmpeg zoom + cut recipe instead.'); } };
  return <main className="forge-main subpage export-room"><section className="page-intro"><p className="kicker">FINAL CHECK</p><h1>Export room</h1><p>Preview the emotional cut. Export only when every gate is green.</p></section><GateStrip gates={gates} /><section className="export-grid"><div className="export-preview"><span>10s MOTION PREVIEW</span><div className="export-monitor"><div className="monitor-a"><b>{project.sceneA.headline}</b><small>zoom in</small></div><div className="monitor-cut">HARD CUT</div><div className="monitor-b"><b>{project.sceneB.headline}</b><small>{project.sceneB.motion} camera</small></div></div><p>Audio: <b>{project.audio}</b> · 30 fps · 1080 × 1920</p></div><div className="export-actions"><button className="export-button" disabled={!allGreen || exporting} onClick={startExport}>{exporting ? 'Rendering WebM…' : allGreen ? 'Export WebM' : 'Export (gates green only)'}</button><p>{status || (allGreen ? 'WebM is offered where your browser supports it. MP4 is never claimed unless created.' : 'Fix the red gates before export.')}</p><button className="recipe-button" onClick={async () => { await navigator.clipboard?.writeText(recipe); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }}>{copied ? 'Recipe copied' : 'Copy ffmpeg zoom + cut recipe'}</button><label className="permalink-label">Instagram reel permalink<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.instagram.com/reel/..." /></label><div className={`permalink-result ${validReel ? 'pass' : 'fail'}`}><b>{validReel ? 'READY FOR /REEL/' : 'PERMALINK CHECK'}</b><span>{permalinkText}</span></div><a className="reference-link" href="https://www.instagram.com/p/DcV6RYjkQaU/" target="_blank" rel="noreferrer">Reference: a hook that worked before ↗</a></div></section></main>;
}

export default function ReelForge({ view }: { view: View }) { const forge = useForge(); return <><Topbar view={view} slots={forge.slots} />{view === 'studio' && <Studio forge={forge} />}{view === 'library' && <Library forge={forge} />}{view === 'packet' && <PacketEditor forge={forge} />}{view === 'gates' && <GateBoard forge={forge} />}{view === 'export' && <ExportRoom forge={forge} />}<footer className="forge-footer"><span>NOH | AI at work</span><span>Emotional recreate. Not two PNGs taped together.</span><span>Created with Grok</span></footer></>; }
